### ISSUE TITLE
[suggestion] add support for concat option (eg {newLine: ';'} )

### ISSUE THREAD

**Issue by pcxiong** [jonkemp/gulp-useref#151]
would be useful  :smile: 

thanks

**Comment by jonkemp** [comment]
I'm afraid I don't understand the request.

**Comment by steveluscher** [comment]
I think @pcxiong is talking about a custom separator between files. I just ran into a problem where some off-the-shelf JS without semicolons resulted in a concatenated file that fatals upon evaluation. It would be handy to be able to specify a custom separator, or a function that generates a custom separator.

**Comment by codeBelt** [comment]
Is there anyway you can add this feature soon?

You can see that [gulp-concat](https://github.com/contra/gulp-concat#usage) has the ```{newLine: ';'}``` feature.

I would be happen even if you just added a semicolon to the end of every file's content as a safeguard. 

The reason this is an issue is because some libraries are missing that end semicolon and when the files are concatenated together code merges and causes ```TypeError```.

**Comment by jonkemp** [comment]
https://github.com/jonkemp/gulp-useref/commit/524467db47f10d95b7da987f8374d8307d7a74da

Would still like to add tests for this.

**Comment by jonkemp** [comment]
Done.
