### ISSUE TITLE
Error generating files in subfolder

### ISSUE THREAD

**Issue by CesarDenis** [jonkemp/gulp-useref#186]
Hello I have a problem to generate my final files. I use the [generator-webapp](https://github.com/yeoman/generator-webapp)

When the `html` task will generate the subfolder files it displays error:

``` console
[09:15:08] Finished 'views' after 10 s
[09:15:08] Starting 'html'...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Error: File not found with singular glob: /Users/macweb01/Sites/ccr/ras/styles/main.css
    at DestroyableTransform.<anonymous> (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/lib/streamManager.js:90:36)
    at emitOne (events.js:95:20)
    at DestroyableTransform.emit (events.js:182:7)
    at emitOne (events.js:90:13)
    at DestroyableTransform.emit (events.js:182:7)
    at Glob.<anonymous> (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/index.js:38:16)
    at Glob.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Glob.emit (events.js:182:7)
    at Glob._finish (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
    at RES (/Users/macweb01/Sites/ccr/ras/node_modules/inflight/inflight.js:23:14)
```

It seems that the error is in the plugin `useref`.

``` js
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
```

Already changed the `option.base` and the same error happens

``` js
    .pipe($.useref({searchPath: ['.tmp', 'app', '.'], base: 'app' }))
```

To be able to generate the files necessary to change the layout:

This:

``` html
<!-- build:css ../styles/main.css -->
<link rel="stylesheet" href="../styles/main.css">
<!-- endbuild -->
```

For this:

``` html
<!-- build:css ../styles/main.css -->
<link rel="stylesheet" href="/app/styles/main.css">
<!-- endbuild -->
```

If wanted to see my [gulpfile](https://www.dropbox.com/s/smi5tklri463v85/gulpfile.babel.js?dl=0)

**Comment by dariospadoni** [comment]
I had a similar issues, useref could not find a file and I solved by using its transformPath property to make it search in the right folder. In my case it was something like this:
```
useref({
        transformPath: function(filePath) {
              return filePath.replace('projectName/app','app')
         }
 })
```

**Comment by CesarDenis** [comment]
It works @dariospadoni, but he is now creating the styles and scripts folders in the project root. :sweat:

**Comment by mgazelle** [comment]
I am struggeling with this modul as it is not generating the needed output.

the source HTML:

<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>C4T marketing - A full service digital agency</title><meta name="description" content="A full service digital agency for social marketing, search marketing, mobile marketing, consumer insights, strategy, creativity &amp; technology"><meta name="author" content="C4T marketing"><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"><link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.3/css/bootstrapValidator.min.css"><link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"><link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet" type="text/css"><link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"><link href="http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic" rel="stylesheet" type="text/css"><link href="../css/styles.css" rel="stylesheet"><link rel="image_src" href="thumbnail.png"><link rel="icon" type="image/png" href="../img/favicon.png"></head><body data-spy="scroll" data-target=".navbar" data-offset="61"><script id="__bs_script__">//<![CDATA[ document.write("<script async src='/browser-sync/browser-sync-client.2.12.3.js'><\/script>".replace("HOST", location.hostname)); //]]></script> 

The gulpfile block:

var gulp = require('gulp'),
watch = require('gulp-watch'),
concat = require('gulp-concat'),
uglify = require('gulp-uglify'),
stripDebug = require('gulp-strip-debug'),
cleanCSS = require('gulp-clean-css'),
concatCSS = require('gulp-concat-css'),
browserSync = require('browser-sync'),
connect = require('gulp-connect-php'),
sass = require('gulp-ruby-sass'),
notify = require('gulp-notify'),
bower = require('gulp-bower'),
autoprefixer = require('gulp-autoprefixer'),
jsonminify = require('gulp-jsonminify'),
gutil = require('gulp-util'),
data = require('gulp-data'),
jade = require('gulp-jade'),
html_i18n = require('gulp-html-i18n'),
plumber = require('gulp-plumber'),
jshint = require('gulp-jshint');
inject = require('gulp-inject');
useref = require('gulp-useref');
debug = require('gulp-debug');
var onError = function(err) {
console.log(err);
}
config = {
srcDir: './src',
sassDir: './src/sass',
scriptDir: './src/js',
bowerDir: './bower_components',
nodeDir: './node_modules',
imgDir: './src/img',
langDir: './src/lang',
svgDir: './src/svg',
htmlDir: './src/html',
incDir: './src/inc',
phpDir: './src/php',
distDir: './public/' + (gutil.env.build === 'prod' ? 'release' : 'debug'),
production: gutil.env.build === 'prod'
};
gulp.task('useref', function() {
return gulp.src(config.distDir + '/*/.html')
.pipe(debug())
.pipe(useref({searchPath: config.distDir}))
.pipe(gulp.dest(config.distDir))
.on("error", notify.onError(function (error) {
return "Error: " + error.message;
}))
});

Directory Structure

Project Root
|---public
|---release
|---en
|---index.html
|---de
|---index.html
|---js
|---many js files
|---css
|---styles.css
|---debug

Command to produce file

gulp --build=prod useref

Any hint what the problem is?

Thank you
