### ISSUE TITLE
Something wrong with immediate execute function if I won't add ';' before it.

### ISSUE THREAD

**Issue by dupeiduo** [jonkemp/gulp-useref#221]
When I'm using useref and uglify. If one page just has an immediate execution function, it will remove the ',' which at the end of previous page. Then I'll be told it isn't a immediate execute function.

**Comment by jonkemp** [comment]
This looks like a bug report. In order to be as helpful as possible, here are some guidelines for bug reports:

1. **Use the GitHub issue search** &mdash; check if the issue has already been reported.

2. **Check if the issue has been fixed** &mdash; try to reproduce it using the latest `master` or development branch in the repository.

3. **Isolate the problem** &mdash; create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/) and a live example.

A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs. Thanks!

**Comment by dupeiduo** [comment]
OK. Thanks I will do it now.
