### ISSUE TITLE
How to use the newLine option based on the file type?

### ISSUE THREAD

**Issue by phtwo** [jonkemp/gulp-useref#241]
ep: `';'`
it work in js , but cannot be used for css files

**Comment by jonkemp** [comment]
It takes a string, but I'm not sure what will work for CSS files. I didn't know that was an issue.

**Comment by phtwo** [comment]
@jonkemp yes 
JS files use `';'` and skip CSS files. This is what I want.

**Comment by jonkemp** [comment]
There are currently 2 pull requests open that would meet the requirements here. Mine basically just meets the requirements of js files get the newline and CSS files do not.

#249 

The other one uses options to let you specify which file extensions get skipped.

#248 

Can we get some feedback on these? I think my change is fine but I don't want to break everybody's builds since the option has been there a long time.

**Comment by jonkemp** [comment]
Fixed here https://github.com/jonkemp/gulp-useref/pull/249.

**Comment by jonkemp** [comment]
Thanks to @lfurzewaddock for much help in closing this.
